#!/bin/ash

build() {
  add_dir /lroot
  add_dir /troot
  add_binary zramctl
  add_binary mkfs.ext2
  add_binary nproc
  add_binary free
  add_runscript
}

help() {
  cat <<HELPEOF
This hoook overlays a tmpfs on top of root removing persistent writes to root
HELPEOF
}