#!/bin/ash
#vim: set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

#reads a config file line by line
#config format is 'key=value' repeated on any number of lines
IFS='='
while read -r k v
do
  export "oroot_settings_${k}='${v}'"
done </etc/oroot.conf
IFS=

build() {
  add_dir /lroot
  add_dir /troot
  add_binary zramctl
  add_binary mkswap
  add_binary swapon
  add_binary free
  add_binary mkfs.ext2
  add_binary nproc
  if [[ "$oroot_settings_btrfs" != 'false' ]]
  then
    add_binary mkfs.btrfs
    add_binary btrfs
  fi
  add_runscript
}

help() {
  cat <<HELPEOF
This hoook overlays a tmpfs on top of root removing persistent writes to root
HELPEOF
}
