#!/bin/ash

run_hook() {
  if [ "${croot}" ]; then
     $mount_handler /lroot
     zramctl find 1G lzo $(nproc)
     zramctl find 1G lzo $(nproc)
     mkfs.ext2 /dev/zram0
     mount /dev/zram0 /troot
     mkdir /troot/upper
     mkdir /troot/work
     mount croot -t overlay -o lowerdir=/lroot,upperdir=/troot/upper,workdir=/troot/work /new_root
     mount_handler="echo"
 fi;
}