#!/bin/ash

run_hook() {
  if [ "${oroot}" ]; then
     if [ "$(echo $root | grep UUID)" ]; then
        rootdev=$(resolve_device "$root")
        root=$rootdev
        unset rootdev
     fi;
     fsck_root() {
       echo &>/dev/null
     }
     echo "#!/bin/bash
       mount \"$root\" /mnt;
       cd /;
       rsync -a --delete --exclude /usr/bin/overlay_flush etc home opt root srv usr var /mnt/;
       umount /mnt;
       " > /overlay_flush
     chmod ug+x /overlay_flush
     $mount_handler /lroot
     if [ -z "$(lsmod | grep zram | head -1)" ]; then
        modprobe zram num_devices=$(($(nproc)+2))
     fi;
     mem_size=$(free -m | awk '/Mem/ {print int($2)}');
     if [ "${quiet}" ]; then
        zramctl find $(($mem_size/2))M lzo $(nproc) &>/dev/null
      else
        zramctl find $(($mem_size/2))M lzo $(nproc)
     fi;
     if [[ "${oroot}" = "compressed" || "${oroot}" = "live" ]]; then
        if [ "${quiet}" ]; then
           zramctl find $(($mem_size*2))M lzo $(nproc) &>/dev/null
           mkfs.ext2 /dev/zram1 &>/dev/null
         else
           zramctl find $(($mem_size*2))M lzo $(nproc)
           mkfs.ext2 /dev/zram1
        fi;
        mount /dev/zram1 /troot
      elif [ "${oroot}" = "raw" ]; then
        mount troot -t tmpfs -o size=${mem_size}M /troot
     fi;
     unset mem_size;
     if [ "${quiet}" ]; then
        mkswap /dev/zram0 &>/dev/null
        swapon /dev/zram0 &>/devnull
      else
        mkswap /dev/zram0
        swapon /dev/zram0
     fi;
     if [ ! "${oroot}" = "live" ]; then
        mkdir /troot/upper;
        mkdir /troot/work;
        oroot_mount() {
          mount oroot -t overlay -o lowerdir=/lroot,upperdir=/troot/upper,workdir=/troot/work "$1"
          mv /overlay_flush /new_root/usr/bin/
        }
      else
        cp -a /lroot/* /troot/;
        umount /lroot;
        umount /troot;
        oroot_mount() {
          mount /dev/zram1 "$1"
          mv /overlay_flush /new_root/usr/bin/
        }
     fi;
     mount_handler=oroot_mount
  fi;
}